name=Tenergy32Hub GY-NEO-8M GPS
version=1.0.0
author=Tenergy Innovation
maintainer=Tenergy Innovation
sentence=Arduino library for GY-NEO-8M GPS module with U-blox chipset
paragraph=This library provides easy interface to read GPS data from GY-NEO-8M module using NMEA protocol. Compatible with ESP32 and Arduino boards.
category=Sensors
url=https://github.com/tenergyinnovation/tenergy32hub_GY-NEO-8M_Ublox
architectures=*
depends=